# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['say_hello', 'hiSayer']

# Cell
def say_hello(to):
    "Say hello to someone"
    return(f"hello {to}")

# Cell
class hiSayer:
    "Dumb class that spams hi to someone"
    def __init__(self,to):
        self.to = to

    def say(self):
        "Calls function say_hello to say hello"
        return say_hello(self.to)